inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.6.4
  Exclude:
    - vendor/**/*
  UseCache: true
  CacheRootDirectory: tmp/rubocop

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Include:
    - '**/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false
