# This file is for shopify internal development, feel free to ignore.
name: recordstore

up:
  - ruby: 2.3.1
  - bundler

commands:
  test:
    syntax:
      argument: file
      optional: args...
    desc:   'run tests'
    run: |
      if [[ $# -eq 0 ]]; then
        bundle exec rake test
      else
        bundle exec ruby -Itest "$@"
      fi

packages:
  - git@github.com:Shopify/dev-shopify.git
