# This file is for shopify internal development, feel free to ignore.
name: recordstore

up:
  - ruby: 2.3.1
  - bundler

commands:
  test:
    run: bundle exec rake test

packages:
  - git@github.com:Shopify/dev-shopify.git
